// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/fabiansefranek/dbi-perf-tests/components"
	"github.com/fabiansefranek/dbi-perf-tests/handlers"
)

func MongoIndex() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		users := handlers.GetMongoUsers()
		sprints := handlers.GetMongoSprints()
		projects := handlers.GetMongoProjects()
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"title is-4\">Users</p><form action=\"/mongo/users\" method=\"POST\"><div style=\"display: flex; flex-direction:row; justify-content: space-between;\"><input class=\"input\" type=\"text\" name=\"username\" placeholder=\"Username\" required> <input class=\"input\" type=\"text\" name=\"firstName\" placeholder=\"First Name\" required> <input class=\"input\" type=\"text\" name=\"lastName\" placeholder=\"Last Name\" required></div><button class=\"button\" type=\"submit\">Add User</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Table("mongo", "users", []string{"Id", "Name", "First Name", "Last Name"}, users).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <br><hr><br><p class=\"title is-4\">Projects</p><form action=\"/mongo/projects\" method=\"POST\"><div style=\"display: flex; flex-direction:row; justify-content: space-between;\"><input class=\"input\" type=\"text\" name=\"name\" placeholder=\"Project Name\" required> <input class=\"input\" type=\"text\" name=\"identifier\" placeholder=\"Identifier\" required> <input class=\"input\" type=\"text\" name=\"invite_code\" placeholder=\"Invite Code\" required> <input class=\"input\" type=\"number\" name=\"sprint_duration\" placeholder=\"Sprint Duration\" required> <input class=\"input\" type=\"text\" name=\"owner_id\" placeholder=\"Owner Id\" required></div><button class=\"button\" type=\"submit\">Add Project</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Table("mongo", "projects", []string{"Id", "Name", "Identifier", "Invite Code", "Sprint Duration", "Owner Id"}, projects).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <br><hr><br><p class=\"title is-4\">Sprints</p><form action=\"/mongo/sprints\" method=\"POST\"><div style=\"display: flex; flex-direction:row; justify-content: space-between;\"><input class=\"input\" type=\"text\" name=\"name\" placeholder=\"Sprint Name\" required> <input class=\"input\" type=\"text\" name=\"start_date\" placeholder=\"Start Date\" required> <input class=\"input\" type=\"text\" name=\"end_date\" placeholder=\"End Date\" required> <input class=\"input\" type=\"text\" name=\"project_id\" placeholder=\"Project Id\" required></div><button class=\"button\" type=\"submit\">Add Sprint</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Table("mongo", "sprints", []string{"Id", "Sprint Name", "Start Date", "End Date", "Project Id"}, sprints).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
